version: "3"

services:
  mysql:
    restart: always
    image: mysql:latest
    container_name: my-sql-latest
    environment:
      - MYSQL_DATABASE=studentsdb
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - 33080:3306