spring:
  datasource:
    url: jdbc:mysql://localhost:33099/test
    password: password
    username: root
    driver-class-name: "com.mysql.jdbc.Driver"
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update