spring:
  datasource:
    url: jdbc:mysql://localhost:33080/dogs
    password: password
    username: root
    driver-class-name: "com.mysql.cj.jdbc.Driver"
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update